sudo: false

# Protobuf is very expensive to install, so we cache it between builds
before_install:
  - pip install --upgrade pip
  - pip --version

python:
  - "2.7"
install: pip install codecov tox-travis
script: tox
after_success:
  - codecov
