version: 2
workflows:
  version: 2
  tests:
    jobs:
      - format:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - test-3.6:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - test-2.7:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
jobs:
  format:
    docker:
    - image: python:3.6-slim
    steps:
    - checkout
    - run:
        name: Install Python dependencies.
        command: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt
    - run:
        name: Install pylint.
        command: pip install pylint
    - run:
        name: Run pylint.
        command: pylint -f colorized -E plugin --ignore plugin/cli,plugin/pb2
  test-3.6:
    docker:
    - image: python:3.6-stretch
    steps:
    - checkout
    - run:
        name: Install Python dependencies.
        command: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt
    - run:
        name: Checkout googleapis/googleapis.
        command: git clone git@github.com:googleapis/googleapis.git
    - run:
        name: Install protoc.
        command: |
          mkdir -p /usr/src/protoc/
          curl --location https://github.com/google/protobuf/releases/download/v3.11.2/protoc-3.11.2-linux-x86_64.zip --output /usr/src/protoc/protoc-3.11.2.zip
          cd /usr/src/protoc/
          unzip protoc-3.11.2.zip
          ln -s /usr/src/protoc/bin/protoc/ usr/bin/protoc
    - run:
        name: Run tests.
        command: pytest /test
  test-2.7:
    docker:
    - image: python:2.7-stretch
    steps:
    - checkout
    - run:
        name: Install Python dependencies.
        command: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt
    - run:
        name: Checkout googleapis/googleapis.
        command: git clone git@github.com:googleapis/googleapis.git
    - run:
        name: Install protoc.
        command: |
          mkdir -p /usr/src/protoc/
          curl --location https://github.com/google/protobuf/releases/download/v3.11.2/protoc-3.11.2-linux-x86_64.zip --output /usr/src/protoc/protoc-3.11.2.zip
          cd /usr/src/protoc/
          unzip protoc-3.11.2.zip
          ln -s /usr/src/protoc/bin/protoc/ usr/bin/protoc
    - run:
        name: Run tests.
        command: pytest /test

